# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

include:
- project: 'dhei/teams/pandora/gitlab-ci-templates'
  file: '/products/horizon/HorizonComponent.Pipeline.gitlab-ci.yml'
  ref: chore/push-to-artifactory

variables:
  JAVA_BUILD_IMAGE: trusted.artifactory.devops.telekom.de/mcicd-internal-oci/community/jdk:21.0.11
  DS_JAVA_VERSION: 21
  TARGET_IMAGE_SUBGROUP: horizon