# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

server:
  port : 8090
spring:
  zipkin:
    enabled: false

kubernetes:
  enabled: true
  kubeConfigPath: ${user.home}/.kube/config
  informer:
    namespace: integration
    clusterWideAccess: true

horizon:
  cache:
    enabled: true
  kafka:
    bootstrapServers: ${COMET_KAFKA_BROKERS:localhost:9092}
    groupId: ${COMET_KAFKA_GROUP_ID:comet}
    partitionCount: ${COMET_KAFKA_PARTITION_COUNT:16}
    consumerThreadpoolSize: ${COMET_KAFKA_CONSUMER_THREADPOOL_SIZE:4096}
    consumerQueueCapacity: ${COMET_KAFKA_CONSUMER_QUEUE_CAPACITY:8192}
  victorialog:
    enabled: true
    collectorUrl: http://localhost:8428/api/v1/import
    clientId: comet
    batchSize: 10


logging:
  level:
    root: INFO
    de.telekom: DEBUG

comet:
  security:
    # Must be lower-case and comma-separated, can be regex
    headerPropagationBlacklist: ${COMET_HEADER_PROPAGATION_BLACKLIST:x-spacegate-token,authorization,content-length,host,accept.*,x-forwarded.*}
  callback:
    max-connections: ${COMET_MAX_CONNECTIONS:10}
    max-timeout: ${COMET_MAX_TIMEOUT:30000}
    max-retries: ${COMET_MAX_RETRIES:10}
    initial-backoff-interval-ms: ${COMET_INITIAL_BACKOFF_INTERVAL_MS:100}
    max-backoff-interval-ms: ${COMET_MAX_BACKOFF_INTERVAL_MS:60000}
    backoff-multiplier: ${COMET_BACKOFF_MULTIPLIER:2.0}
    successful-status-codes: ${COMET_SUCCESSFUL_STATUS_CODES:200,201,202,204}
    redelivery-status-codes: ${COMET_REDELIVERY_STATUS_CODES:401,429,502,503,504}
    redelivery-threadpool-size: ${COMET_REDELIVERY_THREADPOOL_SIZE:10}
    redelivery-queue-capacity: ${COMET_REDELIVERY_QUEUE_CAPACITY:2147483647}